version: 2.1

orbs:
  python: circleci/python@1.2

executors:
  base_image:
    docker:
      - image: cimg/base:stable
  python_image:
    docker:
      - image: cimg/python:3.8

jobs:
  build:
    working_directory: ~/cccomplete-1
    executor: python_image
    steps:
      - checkout
      - run:
          name: Run main.py
          command: python src/main.py

  lint:
    working_directory: ~/cccomplete-1
    executor: python_image
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: ~/cccomplete-1/requirements-dev.txt
      - run:
          name: Run Python Linter
          command: pylint src/main.py

workflows:
  build-lint:
    jobs:
      - build
      - lint:
          requires:
            - build
