version: 2.1

orbs:
  python: circleci/python@1.2

executors:
  base_image:
    docker:
      - image: cimg/base:stable
  python_image:
    docker:
      - image: cimg/python:3.8

jobs:
  build:
    working_directory: ~/cccomplete-1
    executor: python_image
    steps:
      - checkout
      - run:
          name: Run main.py
          command: python src/main.py

  lint:
    executor: python_image
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-dev.txt
      - run:
          name: Run Python Linter
          command: pylint src/*.py

  unit-test-1:
    executor: python_image
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-dev.txt
      - run:
          name: Run Unit Test 1
          command: python tests/main-test.py

  unit-test-2:
    executor: python_image
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-dev.txt
      - run:
          name: Run Unit Test 2
          command: python tests/main-test.py

  unit-test-3:
    executor: python_image
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-dev.txt
      - run:
          name: Run Unit Test 3
          command: python tests/main-test.py

workflows:
  build-lint-test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - unit-test-1:
          requires:
            - lint
      - unit-test-2:
          requires:
            - lint
      - unit-test-3:
          requires:
            - lint
