version: 2.1

orbs:
  python: circleci/python@1.2
  hadolint: lansweeper/hadolint@0.0.4
  build-and-scan-image: shibataka000/build-and-scan-image@0.0.2

executors:
  docker_publisher:
    environment:
      IMAGE_NAME: vdigital/ccomplete-1
    docker:
      - image: cimg/base:stable
  python_image:
    docker:
      - image: cimg/python:3.8

jobs:
  build:
    working_directory: ~/cccomplete-1
    executor: python_image
    steps:
      - checkout
      - run:
          name: Run main.py
          command: python src/main.py

  python-lint:
    executor: python_image
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-dev.txt
      - run:
          name: Run Python Linter
          command: pylint src/*.py

  unit-test-1:
    executor: python_image
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-dev.txt
      - run:
          name: Run Unit Test 1
          command: python tests/main-test.py

  unit-test-2:
    executor: python_image
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-dev.txt
      - run:
          name: Run Unit Test 2
          command: python tests/main-test.py

  unit-test-3:
    executor: python_image
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-dev.txt
      - run:
          name: Run Unit Test 3
          command: python tests/main-test.py

  dockerfile-lint:
    executor: docker_publisher
    steps:
      - checkout
      - hadolint:
          install:
          lint:

  deploy-to-dockerhub:
    executor: docker_publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Dockerhub
          command: docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASSWORD}"
      - run:
          name: Build Docker Image
          command: docker build -t ${IMAGE_NAME}:$CIRCLE_SHA1 .
      - run:
          name: Tag and Publish Image to DockerHub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
              docker tag ${IMAGE_NAME}:$CIRCLE_SHA1 ${IMAGE_NAME}:stable-${CIRCLE_BUILD_NUM} && docker push ${IMAGE_NAME}:stable-${CIRCLE_BUILD_NUM}
            elif [ "${CIRCLE_BRANCH}" == "staging" ]
            then
              docker tag ${IMAGE_NAME}:$CIRCLE_SHA1 ${IMAGE_NAME}:staging-${CIRCLE_BUILD_NUM} && docker push ${IMAGE_NAME}:staging-${CIRCLE_BUILD_NUM}
            else
              docker tag ${IMAGE_NAME}:$CIRCLE_SHA1 ${IMAGE_NAME}:develop-${CIRCLE_BUILD_NUM} && docker push ${IMAGE_NAME}:develop-${CIRCLE_BUILD_NUM}
            fi

workflows:
  build-lint-test-deploy:
    jobs:
      - build
      - python-lint:
          requires:
            - build
      - unit-test-1:
          requires:
            - python-lint
      - unit-test-2:
          requires:
            - python-lint
      - unit-test-3:
          requires:
            - python-lint
      - deploy-to-dockerhub:
          requires:
            - unit-test-1
            - unit-test-2
            - unit-test-3
          filters:
            branches:
              only:
                - master
                - staging
                - develop
