version: 2.1

orbs:
  python: circleci/python@1.2

executors:
  base_image:
    docker:
      - image: cimg/base:stable
  python_image:
    docker:
      - image: cimg/python:3.8

jobs:
  build:
    working_directory: ~/cccomplete-1
    executor: python_image
    steps:
      - checkout
      - run:
          name: Print Working Directory
          command: pwd
      - run:
          name: List Files
          command: ls -la

workflows:
  build-test-deploy:
    jobs:
      - build
